Repository oacore/dashboard, pull requests merged in 2020-02, with the labels that each got.

#120 Fix repository select for Firefox and Safari
  design/select/index.jsx
Labels: 🐛 bug

#123 Fix text cut in expanded rows
  components/table/TableRowExpanded.jsx
  components/table/index.css
Labels: 🐛 bug

#124 Allow to open full texts from Content page
  pages/data-providers/[data-provider-id]/content.jsx
Labels: :fire: refactoring, feature, 💅 styling

#125 Fix no compliance level data reporting
  pages/data-providers/[data-provider-id]/deposit-dates.jsx
  texts/depositing/chart.yml
  texts/depositing/index.js
  texts/depositing/no-data.md
Labels: 🐛 bug

#122 Extend overview chart data to show 4 years period, make it relative to data
  pages/data-providers/[data-provider-id]/overview.jsx
Labels: ❔question, 💅 styling

#129 Revert bump core-js from 3.4.2 to 3.6.4
  package-lock.json
  package.json
Labels: 🐛 bug

#130 Add google analytics
  .env.example
  .eslintrc.yml
  next.config.js
  package-lock.json
  package.json
  pages/_app/index.jsx
  utils/analytics.js
Labels: feature

#121 Fix firefox layout
  design/overlay/index.css
  pages/data-providers/[data-provider-id]/overview.css
  pages/data-providers/[data-provider-id]/overview.jsx
Labels: 🐛 bug

#126 Force using production API if NODE_ENV is production
  api/index.js
  public/login.html
Labels: :fire: refactoring, 🐛 bug

#134 Add depositing data explanation text
  pages/data-providers/[data-provider-id]/deposit-dates.jsx
  texts/depositing/chart.md
  texts/depositing/chart.yml
  texts/depositing/index.js
Labels: :book: documentation, :fire: refactoring, 💅 styling

#135 Bring development environment back!
  api/index.js
  config.js
  pages/_app/index.jsx
Labels: :fire: refactoring

#137 Style chart tooltip
  components/time-lag-chart/index.css
  components/time-lag-chart/tooltip.jsx
Labels: 💅 styling

#140 CSP
  .stylelintrc.yml
  components/published-toggle/index.css
  pages/_app/index.jsx
  public/login.css
  public/login.html
  public/login.js
  public/logout.css
  public/logout.html
  public/sanitize.css
Labels: ✨ enhancement

#139 Table refactor
  api/index.js
  components/table/LoadMoreRow.jsx
  components/table/NoDataFoundRow.jsx
  components/table/TablePage.jsx
  components/table/TableRow.jsx
  components/table/TableRowExpanded.jsx
  components/table/index.jsx
  pages/data-providers/[data-provider-id]/deposit-dates.jsx
  store/deposit-dates.js
  store/helpers/invalidatePreviousRequests.js
  store/works.js
  utils/promise.js
Labels: :fire: refactoring

#143 Remove 'git add' from lint-staged config
  .lintstagedrc
Labels: 🐛 bug

#141 Allow to copy text in table
  components/table/index.jsx
Labels: 🐛 bug

#146 Move data fetch from Table to Store
  components/table/index.jsx
  pages/data-providers/[data-provider-id]/content.jsx
  pages/data-providers/[data-provider-id]/deposit-dates.jsx
  store/deposit-dates.js
  store/helpers/invalidatePreviousRequests.js
  store/helpers/pages/index.js
  store/helpers/pages/page.js
  store/helpers/pages/pages.js
  store/works.js
  utils/linkedList/index.js
  utils/linkedList/linkedList.js
  utils/linkedList/linkedListNode.js
Labels: :fire: refactoring

#147 Redirect to display page in tables
  components/document-link/index.jsx
  components/table/TableRow.jsx
  components/table/index.jsx
  pages/data-providers/[data-provider-id]/content.jsx
  pages/data-providers/[data-provider-id]/deposit-dates.jsx
  store/helpers/pages/pages.js
Labels: ✨ enhancement

#150 Fix CSP for styles
  pages/_app/index.css
  pages/_app/index.jsx
Labels: 🐛 bug

#152 Allow to pass body to apiRequest
  api/index.js
Labels: :book: documentation, :fire: refactoring, ✨ enhancement

#153 Bump design
  components/application/activity-select/index.jsx
  package-lock.json
  package.json
  public/icons/calendar-check.svg
  public/icons/dashboard.svg
  public/icons/document.svg
Labels: :fire: refactoring
