Repository oacore/dashboard, pull requests merged in 2020-04, with the labels that each got.

#252 Fix table styling
  components/table/index.jsx
  pages/data-providers/[data-provider-id]/content.css
  pages/data-providers/[data-provider-id]/deposit-dates.css
  pages/data-providers/[data-provider-id]/deposit-dates.jsx
  pages/data-providers/[data-provider-id]/doi.css
  pages/data-providers/[data-provider-id]/doi.jsx
Labels: 🐛 bug, 💅 styling

#259 Move login to /login
  components/application/activity-select/index.jsx
  components/application/logout.jsx
  components/application/repository-select.jsx
  pages/_app/index.css
  pages/_app/index.jsx
  pages/data-providers/[data-provider-id]/overview.jsx
  pages/data-providers/[data-provider-id]/plugins/index.jsx
  pages/index.js
  pages/login.css
  pages/login.jsx
  public/secure/login.css
  public/secure/login.html
  public/secure/login.js
  store/root.js
Labels: :recycle: refactoring, proposal

#261 Bug fixes
  design/drawer/item.jsx
  package-lock.json
  package.json
  pages/_app/index.jsx
  pages/data-providers/[data-provider-id]/overview.jsx
Labels: 🐛 bug

#267 Unify table with the rest of codebase
  components/table/column.jsx
  components/table/index.js
  components/table/load-more-row.jsx
  components/table/no-data-found-row.jsx
  components/table/row.jsx
  components/table/sidebar.jsx
  components/table/styles.css
  components/table/table.jsx
  package-lock.json
  package.json
  pages/data-providers/[data-provider-id]/doi.jsx
  utils/withErrorBoundary.jsx
Labels: :recycle: refactoring

#262 Handle login in iframe only
  pages/_app/index.jsx
  pages/login.jsx
  public/secure/login.js
Labels: :recycle: refactoring

#271 Accept default search params from URL in API request
  api/index.js
  store/deposit-dates.js
Labels: 🐛 bug

#265 Upgrade @oacore/design to 0.1.0, add library configuration
  components/application/activity-select/index.jsx
  components/document-link/index.jsx
  components/takedown/index.jsx
  design.config.js
  package-lock.json
  package.json
  pages/data-providers/[data-provider-id]/content.jsx
  pages/data-providers/[data-provider-id]/doi.jsx
  store/activities.js
Labels: :recycle: refactoring, ✨ enhancement

#273 Add publication dates chart
  components/stacked-vertical-bar-chart/index.jsx
  components/stacked-vertical-bar-chart/styles.css
  pages/data-providers/[data-provider-id]/deposit-dates.css
  pages/data-providers/[data-provider-id]/deposit-dates.jsx
  store/deposit-dates.js
  texts/depositing/index.js
  texts/depositing/publication-dates.yml
Labels: ✨ enhancement

#269 Add Cross Repository Check card
  pages/data-providers/[data-provider-id]/deposit-dates.css
  pages/data-providers/[data-provider-id]/deposit-dates.jsx
  store/deposit-dates.js
  texts/depositing/chart.md
  texts/depositing/cross-repository-check.md
  texts/depositing/index.js
Labels: ✨ enhancement

#276 Fix Content Table
  components/table/sidebar.jsx
  components/table/styles.module.css
Labels: 🐛 bug

#278 Use real non compliant percentage
  pages/data-providers/[data-provider-id]/deposit-compliance.jsx
  pages/data-providers/[data-provider-id]/overview.jsx
Labels: 🐛 bug

#279 Observer iframe after ref is assigned
  components/forms/iframe-form.jsx
Labels: 🐛 bug

#281 Temporary fix now.sh deployment
  package.json
Labels: 🐛 bug

#282 Fix resize observer
  components/forms/iframe-form.jsx
Labels: 🐛 bug

#277 Use MobX react lite over mobx-react
  components/table/column.jsx
  components/table/row.jsx
  package-lock.json
  package.json
  pages/data-providers/[data-provider-id]/content.jsx
  store/index.jsx
Labels: :recycle: refactoring

#286 Fix autofill
  package-lock.json
  package.json
  public/secure/invitation.css
  public/secure/reset.css
Labels: 🐛 bug
