Repository oacore/dashboard, pull requests merged in 2020-05, with the labels that each got.

#290 Show matching icon in deposit table
  pages/data-providers/[data-provider-id]/deposit-compliance.jsx
  pages/data-providers/[data-provider-id]/deposit-compliance.module.css
Labels: ✨ enhancement

#291 Show better description when all outputs are (non) compliant
  pages/data-providers/[data-provider-id]/deposit-compliance.jsx
  pages/data-providers/[data-provider-id]/overview.jsx
  texts/depositing/index.js
  texts/depositing/overview.yml
Labels: ✨ enhancement

#298 Make select more general
  components/application/repository-select.module.css
  design/select/index.jsx
  design/select/styles.module.css
Labels: 💅 styling

#304 Remove svgstore, as it's not used directly
  package.json
Labels: dependencies

#303 Show user name in AppBar when it's available
  components/application/logout.jsx
Labels: ✨ enhancement

#302 Run DepositDases requests sequentially
  store/deposit-dates.js
Labels: 🐛 bug

#305 Move DOI page to templates
  next.config.js
  pages/data-providers/[data-provider-id]/doi.jsx
  templates/doi/cards/coverage-card.jsx
  templates/doi/cards/export-card.jsx
  templates/doi/cards/index.js
  templates/doi/cards/table-card.jsx
  templates/doi/index.jsx
  templates/doi/styles.module.css
Labels: :recycle: refactoring, proposal

#307 Fix DOI loading
  templates/doi/cards/coverage-card.jsx
  utils/helpers.js
Labels: 🐛 bug

#308 Move Content to templates
  pages/_app/index.jsx
  pages/data-providers/[data-provider-id]/content.jsx
  store/works.js
  templates/content/cards/table-card.jsx
  templates/content/index.jsx
  templates/content/styles.module.css
Labels: :recycle: refactoring

#311 Move overview tab to templates
  components/link-button/index.jsx
  pages/data-providers/[data-provider-id]/overview.jsx
  templates/overview/cards/data-statictics-card.jsx
  templates/overview/cards/depositing-card.jsx
  templates/overview/cards/doi-card.jsx
  templates/overview/cards/index.js
  templates/overview/cards/overview-card.jsx
  templates/overview/cards/placeholder-card.jsx
  templates/overview/index.jsx
  templates/overview/styles.module.css
Labels: :recycle: refactoring

#313 Move Deposit compliance to templates
  pages/data-providers/[data-provider-id]/deposit-compliance.jsx
  templates/deposit-compliance/cards/cross-repository-check-card.jsx
  templates/deposit-compliance/cards/cross-repository-check-redirect-card.jsx
  templates/deposit-compliance/cards/data-overview-card.jsx
  templates/deposit-compliance/cards/deposit-time-lag-card.jsx
  templates/deposit-compliance/cards/index.js
  templates/deposit-compliance/cards/publications-dates-card.jsx
  templates/deposit-compliance/cards/table-card.jsx
  templates/deposit-compliance/index.jsx
  templates/deposit-compliance/styles.module.css
Labels: :recycle: refactoring

#306 Pass label to Select component
  components/application/repository-select.jsx
  design/select/index.jsx
  package-lock.json
  package.json
Labels: 🐛 bug

#315 Use correct title for all pages
  components/title/index.jsx
  pages/data-providers/[data-provider-id]/plugins/discovery.jsx
  pages/data-providers/[data-provider-id]/plugins/index.jsx
  pages/data-providers/[data-provider-id]/plugins/recommender.jsx
  pages/data-providers/[data-provider-id]/settings.jsx
  pages/invitation.jsx
  pages/login.jsx
  pages/reset/[token].jsx
  pages/reset/index.jsx
  templates/content/index.jsx
  templates/deposit-compliance/index.jsx
  templates/doi/index.jsx
  templates/overview/index.jsx
Labels: ✨ enhancement

#316 Fix now.sh build
  package.json
Labels: 🐛 bug

#314 Hide activities when user has been accidentally logged out
  pages/_app/index.jsx
Labels: 🐛 bug

#287 Add Issues tab
  components/table/table.jsx
  pages/_app/index.jsx
  pages/data-providers/[data-provider-id]/issues.jsx
  pages/data-providers/[data-provider-id]/issues.module.css
  pages/data-providers/[data-provider-id]/overview.jsx
  store/activities.js
  store/helpers/pages/pages.js
  store/issues.js
  store/root.js
  templates/overview/cards/data-statictics-card.jsx
  templates/overview/index.jsx
  templates/overview/styles.module.css
  texts/index.js
  texts/issues/index.js
  texts/issues/issues.yml
  texts/issues/messages.yml
  texts/navigation.yml
Labels: ✨ enhancement

#204 Fix sidebar not closing after navigation
  components/layout/side-bar.jsx
Labels: 🐛 bug

#318 Fix select
  design/select/index.jsx
Labels: 🐛 bug

#320 Remove dayjs in favour of Int.DateTimeFormat
  package-lock.json
  package.json
  pages/_app/index.jsx
  pages/data-providers/[data-provider-id]/issues.jsx
  templates/content/cards/table-card.jsx
  templates/deposit-compliance/cards/table-card.jsx
  templates/overview/cards/data-statictics-card.jsx
  utils/helpers.js
Labels: :recycle: refactoring

#319 Issues to templates
  components/table/table.jsx
  pages/data-providers/[data-provider-id]/issues.jsx
  templates/issues/cards/errors-overview-card.jsx
  templates/issues/cards/harvesting-overview-card.jsx
  templates/issues/cards/index.js
  templates/issues/cards/table-card.jsx
  templates/issues/index.jsx
  templates/issues/styles.module.css
Labels: :recycle: refactoring, 🐛 bug

#323 Add quotes to the copy command, fix build
  package.json
Labels: 🐛 bug

#322 Upgrade packages
  package-lock.json
  package.json
Labels: dependencies

#324 Add issues to the menu
  components/application/activities.js
Labels: 🐛 bug

#325 Review OAI identifier and endpoint issues
  texts/issues/messages.yml
Labels: 🚧 in progress

#327 Show correct non-compliant count
  store/deposit-dates.js
  templates/deposit-compliance/cards/data-overview-card.jsx
Labels: 🐛 bug

#328 Move global CSS to a subdirectory
  package.json
  public/secure/invitation.html
  public/secure/login.html
  public/secure/reset.html
Labels: 🐛 bug

#329 Cut data overview buttons text
  templates/overview/cards/data-statictics-card.jsx
Labels: 🐛 bug

#330 Widen Record column in Issues table
  templates/issues/styles.module.css
Labels: 🐛 bug

#332 Change publication date calculation description
  texts/depositing/chart.md
Labels: :book: documentation

#331 Change deposit dates card title, add description
  templates/deposit-compliance/cards/table-card.jsx
Labels: ✨ enhancement

#299 Redirect to the previous page after logging in
  pages/_app/index.jsx
  pages/login.jsx
  public/secure/login.js
Labels: ✨ enhancement, ❔question

#338 Remove log timing
  store/root.js
  utils/analytics.js
Labels: :recycle: refactoring

#339 Add '202 Accepted' handling for cross-deposit-lag
  api/index.js
  store/deposit-dates.js
Labels: 🐛 bug

#340 Add cross-repository-check message for 0 value
  templates/deposit-compliance/cards/cross-repository-check-card.jsx
  texts/depositing/cross-repository-check.md
  texts/depositing/cross-repository-check/failure.md
  texts/depositing/cross-repository-check/index.js
  texts/depositing/cross-repository-check/index.yml
  texts/depositing/cross-repository-check/success.md
  texts/depositing/index.js
Labels: ✨ enhancement

#341 Fix misspelled Url suffix
  pages/data-providers/[data-provider-id]/deposit-compliance.jsx
  store/deposit-dates.js
  templates/deposit-compliance/cards/cross-repository-check-card.jsx
  templates/deposit-compliance/index.jsx
Labels: :recycle: refactoring

#344 Show correct message when invitation cannot be send
  store/organisation.js
Labels: 🐛 bug

#343 Fix history loop
  pages/_app/hooks.js
Labels: 🐛 bug

#349 Remove the button from publication dates overview
  templates/deposit-compliance/cards/publications-dates-card.jsx
  templates/deposit-compliance/styles.module.css
Labels: :recycle: refactoring

#348 Remove ORCID card placeholder
  templates/overview/index.jsx
Labels: :recycle: refactoring

#351 Change development API URL
  config.js
Labels: 🐛 bug
