Repository oacore/dashboard, pull requests merged in 2020-01, with the labels that each got.

#44 Add @oacore/texts package emulation
  .eslintrc.yml
  next.config.js
  package-lock.json
  package.json
  texts/index.js
  webpack/.eslintrc.yml
  webpack/camelcase-loader.js
Labels: dependencies, enhancement

#65 Sortable columns
  components/application/activity-select/index.jsx
  components/application/index.jsx
  components/application/repository-select.jsx
  components/table/TablePage.jsx
  components/table/index.jsx
  design/class-name-helpers.css
  design/index.js
  design/select/index.jsx
  package-lock.json
  package.json
  pages/data-providers/[data-provider-id]/deposit-dates.jsx
Labels: feature

#67 Connect tables into API
  components/application/repository-select.jsx
  components/published-toggle/index.jsx
  components/table/LoadMoreRow.jsx
  components/table/LoadingRow.jsx
  components/table/NoDataFoundRow.jsx
  components/table/TablePage.jsx
  components/table/TableRow.jsx
  components/table/TableRowExpanded.jsx
  components/table/index.jsx
  package-lock.json
  package.json
  pages/_app/index.jsx
  pages/data-providers/[data-provider-id]/content.css
  pages/data-providers/[data-provider-id]/content.jsx
  pages/data-providers/[data-provider-id]/deposit-dates.css
  pages/data-providers/[data-provider-id]/deposit-dates.jsx
  pages/data-providers/[data-provider-id]/plugins.jsx
  store/index.jsx
  store/store.js
  store/user.js
  store/works.js
Labels: feature

#69 Table Adjustments
  components/published-toggle/index.css
  components/table/index.css
  design/alert/index.css
  design/alert/index.jsx
  design/index.js
  package-lock.json
  package.json
  pages/data-providers/[data-provider-id]/content.css
  pages/data-providers/[data-provider-id]/content.jsx
  pages/data-providers/[data-provider-id]/deposit-dates.css
  pages/data-providers/[data-provider-id]/deposit-dates.jsx
Labels: feature, 🐛 bug

#73 Deposit Time Lag Chart
  components/time-lag-chart/data.jsx
  components/time-lag-chart/index.css
  components/time-lag-chart/index.jsx
  package-lock.json
  package.json
  pages/data-providers/[data-provider-id]/content.jsx
  pages/data-providers/[data-provider-id]/deposit-dates.jsx
Labels: feature

#78 Fix <col> element placement, add <colgroup>
  components/table/index.jsx
Labels: 🐛 bug

#85 Table sort functionality
  components/table/index.jsx
  pages/data-providers/[data-provider-id]/content.jsx
  pages/data-providers/[data-provider-id]/deposit-dates.jsx
  store/depositDates.js
  store/helpers/order.js
  store/works.js
Labels: feature

#86 Calculate compliance level
  components/time-lag-chart/index.jsx
  pages/data-providers/[data-provider-id]/deposit-dates.jsx
  store/data.jsx
  store/depositDates.js
Labels: feature

#84 Add Overlay component
  design/index.js
  design/overlay/index.css
  design/overlay/index.jsx
Labels: feature, 💅 styling

#90 Add publicDate column to deposit dates table
  components/table/index.jsx
  pages/data-providers/[data-provider-id]/content.jsx
  pages/data-providers/[data-provider-id]/deposit-dates.css
  pages/data-providers/[data-provider-id]/deposit-dates.jsx
Labels: :fire: refactoring, 🐛 bug

#98 Fix GET params & HEAD method in API request
  api/index.js
Labels: 🐛 bug

#99 Fix [object Object] in exported deposit dates CSV
  store/deposit-dates.js
Labels: 🐛 bug

#100 Disable Take down buttons
  components/published-toggle/index.css
  components/published-toggle/index.jsx
  pages/data-providers/[data-provider-id]/content.jsx
Labels: 🐛 bug

#93 Logout
  components/application/index.jsx
  components/application/logout.css
  components/application/logout.jsx
  public/login.html
Labels: feature

#97 Table component abort useless requests
  api/index.js
  components/table/TablePage.jsx
  components/table/TableRow.jsx
  components/table/index.jsx
  pages/data-providers/[data-provider-id]/content.jsx
  pages/data-providers/[data-provider-id]/deposit-dates.jsx
  store/deposit-dates.js
  store/helpers/page.js
  store/root.js
  store/user.js
  store/works.js
  utils/debounce.js
  utils/promise.js
Labels: work-in-progress, 🐛 bug

#103 Speedup deposit dates page rendering
  components/time-lag-chart/index.jsx
Labels: :fire: refactoring

#102 Sentry integration
  .env.example
  .eslintrc.yml
  .gitignore
  components/error-boundary/index.jsx
  components/table/index.jsx
  next.config.js
  package-lock.json
  package.json
  pages/_app/index.jsx
  utils/sentry.js
  utils/withErrorBoundary.jsx
Labels: feature

#104 Show warning message when wrong credentials passed
  public/login.html
Labels: feature

#106 Table fix
  components/table/index.jsx
  pages/data-providers/[data-provider-id]/content.jsx
  store/deposit-dates.js
  store/helpers/page.js
  store/works.js
Labels: 🐛 bug
