Repository oacore/dashboard, pull requests merged in 2020-06, with the labels that each got.

#354 Fix deposit compliance level reporting for 0 counted
  templates/deposit-compliance/cards/data-overview-card.jsx
Labels: 🐛 bug

#355 Fix number formatting for publication dates overview
  components/stacked-vertical-bar-chart/index.jsx
Labels: 💅 styling

#357 Fix view button at Issues
  templates/issues/cards/table-card.jsx
Labels: 🐛 bug

#359 Fix sidebar scrolling and styles
  components/table/sidebar.jsx
  components/table/styles.module.css
Labels: 🐛 bug, 💅 styling

#358 Fix lint-staged config for '*.css'
  .lintstagedrc
Labels: 🐛 bug

#361 Fix IRUS half-cut bar captions
  templates/overview/styles.module.css
Labels: 🐛 bug, 💅 styling

#363 Rewrite RIOXX chart onto FlexBox
  templates/overview/cards/rioxx-card.jsx
  templates/overview/styles.module.css
Labels: :recycle: refactoring, 🐛 bug, 💅 styling

#364 Fix export enabled/disabled for DOIs
  pages/data-providers/[data-provider-id]/doi.jsx
  store/doi.js
  templates/doi/index.jsx
Labels: 🐛 bug

#326 Rewrite table to functional component
  components/table/body.jsx
  components/table/footer.jsx
  components/table/header.jsx
  components/table/hooks/use-dynamic-data.js
  components/table/hooks/use-table-config.js
  components/table/hooks/use-table-state.js
  components/table/table.jsx
  store/helpers/pages/pages.js
  templates/content/cards/table-card.jsx
  templates/deposit-compliance/cards/table-card.jsx
  templates/doi/cards/table-card.jsx
  templates/issues/cards/table-card.jsx
  utils/hooks/use-debounced-effect.js
Labels: :recycle: refactoring

#369 Fix undefined data
  store/helpers/pages/pages.js
Labels: 🐛 bug

#366 Rename 'IRUS' to 'Download statistics'
  templates/overview/cards/irus-card.jsx
Labels: 💅 styling

#368 Grey the table out if the result requires payment
  templates/deposit-compliance/cards/table-card.jsx
  templates/deposit-compliance/styles.module.css
  templates/doi/cards/table-card.jsx
  templates/doi/styles.module.css
Labels: 💅 styling

#362 Add HUGE approximation to StackedBarChart
  components/stacked-vertical-bar-chart/index.jsx
  components/stacked-vertical-bar-chart/styles.module.css
Labels: 🐛 bug

#370 Update payment-required wording
  texts/billing/payment-required.md
  texts/depositing/cross-repository-check/payment-required.md
Labels: 💅 styling

#367 Change the email and contact-reason for premium requests
  modules/billing/payment-required/data.js
Labels: 💅 styling

#365 Rename 'Deposit compliance' to 'REF 2021'
  design.config.js
  pages/data-providers/[data-provider-id]/deposit-compliance.jsx
  pages/data-providers/[data-provider-id]/overview.jsx
  templates/deposit-compliance/index.jsx
  templates/deposit-compliance/styles.module.css
  templates/overview/cards/depositing-card.jsx
  templates/overview/index.jsx
  templates/overview/styles.module.css
  texts/depositing/compliance-notice.md
  texts/depositing/index.js
  texts/depositing/intro.md
  texts/depositing/overview.yml
  texts/navigation.yml
Labels: 💅 styling

#372 Restore sidebar size back to 12rem
  components/layout/styles.module.css
Labels: 💅 styling

#374 Fix applying Table.Body callbacks without a reason
  components/table/table.jsx
Labels: 🐛 bug
