Repository oacore/dashboard, pull requests merged in 2020-03, with the labels that each got.

#177 Bump package versions [March]
  package-lock.json
  package.json
  public/sanitize.css
Labels: dependencies

#178 Fix activities
  components/application/activity-select/index.jsx
  components/application/index.jsx
  pages/_app/index.jsx
  store/activities.js
  store/root.js
Labels: :fire: refactoring, proposal

#181 Fix: don't show children in menu
  store/activities.js
Labels: 🐛 bug

#182 Add optimistic takedown
  components/published-toggle/index.jsx
Labels: ✨ enhancement

#183 Fix login redirect
  config.js
Labels: 🐛 bug

#184 Add loading login form instead blank screen
  pages/_app/index.css
  pages/_app/index.jsx
  public/login.css
  public/login.html
  public/login.js
Labels: ✨ enhancement

#189 Fix from param
  store/helpers/pages/page.js
  store/helpers/pages/pages.js
Labels: 🐛 bug

#191 Simplify apiRequest interface
  api/index.js
  store/deposit-dates.js
  store/helpers/invalidatePreviousRequests.js
  store/helpers/pages/pages.js
  store/root.js
  store/user.js
  store/works.js
  utils/promise.js
Labels: :fire: refactoring

#192 Rename deposit dates navigation item
  texts/navigation.yml
Labels: :fire: refactoring

#195 Disable logout container word wrapping
  components/application/logout.css
Labels: 🐛 bug

#200 Fix disabled deposit dates export button
  pages/data-providers/[data-provider-id]/deposit-dates.jsx
Labels: 🐛 bug

#203 Fix API request when method is HEAD
  api/index.js
  store/deposit-dates.js
Labels: 🐛 bug

#209 Fix postInstall script
  package.json
Labels: 🐛 bug

#210 Limit width of user email in the AppBar
  components/application/logout.css
  components/application/logout.jsx
Labels: 🐛 bug

#214 Measure speed of endpoints
  pages/_app/index.jsx
  store/root.js
  utils/analytics.js
Labels: proposal, ✨ enhancement

#211 Redirect users to the legacy Dashboard if access forbidden
  pages/_app/index.jsx
  public/login.js
Labels: ✨ enhancement, 🖥️ backend support needed

#221 Remove @observer from the global App component
  components/application/index.jsx
  components/application/loading-bar.jsx
  pages/_app/index.jsx
Labels: duplicate, 🐛 bug

#224 Reset table size when search/order changes
  components/table/index.jsx
Labels: 🐛 bug
